### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by houseofdoggus** [HeresJohnny320/RequireToFly#1]
Server thread/WARN09:01:53
[hj320]: Task #47 for RequireToFly-by-heresjohnny320 v1.0 generated an exception
Console09:01:53
java.lang.NumberFormatException: Cannot parse null string
at java.lang.Integer.parseInt(Integer.java:630) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:784) ~[?:?]
at flysystem.hj320.fly_system$2.run(fly_system.java:53) ~[?:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by HeresJohnny320** [comment]
the issue has been resolved
